\data \infixl 2 || (A B : \Type)
  | in0 A
  | in1 B
  \where
  {
    \func rec {A B : \Type}
              (C : \Type) (g0 : A -> C) (g1 : B -> C) (x : A || B) : C \elim x
      | in0 a => g0 a
      | in1 b => g1 b
      | _ => {?}

    \func ind {A B : \Type}
              (C : (A || B) -> \Type) (g0 : \Pi(a : A) -> C (in0 a))
              (g1 : \Pi (b : B) -> C (in1 b)) (x : A || B) : C x \elim x
      | in0 a => g0 a
      | in1 b => g1 b
      | _ => {?}
  }

