\import CH1.Def.def

\func C_xx {A B : \Type} : A xx B -> \Type => \lam (u : A xx B) => (pr1 u, pr2 u) = u

\func uniq_xx {A B : \Type} :
  \Pi(w : A xx B) -> (w.1, w.2) = w => indAxxB C_xx (\lam (a : A) (b : B) => idp)

\func uniq_One : \Pi(w : One) -> (w = One.star) => indOne(\lam x => x = star)(idp)

\func uniq_Two : \Pi(w : Two) -> (w = zero) ++ (w = one) =>
  indTwo (\lam (w : Two) => (w = zero) ++ (w = one)) (inl{zero = zero}{zero = one} idp) (inr{one = zero}{one = one} idp)